# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29e04eca5b30dd6bfb030ae94df21e25d7bc28617a5d6f20a0555fa8fc4ed17aa258b5b249873bea307d0ab90523f571528b517783780207941c9821092c4481

test:
  secret_key_base: 88e870b61ba21f4ce6359be12f27a2b1b2826485556551a6fe713e75528c4a65d099105667d4c264dd1b6bce23d70f64531e8d090180a501fe6de27d0e7867e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
